update: 1.16.2
modmuss50/Voyager pull request #2
Opened 2020-08-28 07:46 UTC by syns

Depend on Minecraft Versions affected by the Issue, also make the mod website the Issue to see if it is fixed whenever it finally is.
Should work with the depended versions as far as I'm aware.

2020-08-30 16:01 UTC, modmuss50 commented on src/main/resources/fabric.mod.json
> +    "minecraft": ["1.14", "1.14.1", "1.14.2", "1.14.3", "1.14.4", "1.15", "1.15.1", "1.15.2", "1.16", "1.16.1", "1.16.2"]
Just do `>=1.14`

2020-08-30 16:01 UTC, modmuss50 commented on src/main/resources/fabric.mod.json
> +  "environment": "client",
This is not true, this also happens on servers.

2020-08-30 16:02 UTC, modmuss50 requested changes
Few changes required.

2020-08-31 05:33 UTC, syns commented
Changes added, thanks!

2020-09-02 22:15 UTC, modmuss50 approved these changes

2020-09-02 22:15 UTC, merged